### ISSUE TITLE
Sufixo e máscara de rede devem ser independentes

### ISSUE THREAD

**Issue by hugleo** [Beiriz/GRCN#1]
O número do sufixo não deve ser levado em consideração na geração das regras:

Por exemplo:
o comando abaixo gera 8190 usuários
./cgnat-nft.py 0 192.168.0.0/24 100.200.0.0/19 2000

O comando abaixo não gera nenhum usuário
./cgnat-nft.py 513 192.168.1.0/24 100.201.0.0/19 2000

Ou seja, a rede 100.x.x.x deveria começar sempre do primeiro:
100.x.x.0
100.x.x.1
...

Independente do índice escolhido.

**Comment by Beiriz** [comment]
Isso mesmo. O sufixo é apenas para gerar regras nftables com nomes diferentes. Não influencia nos cálculos.
